name: Update Stewartby Feed
on:
  schedule:
    - cron: '05 08,10,12,15 * * *'
    - cron: '30 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 feedgen

      - name: Run scraper scripts
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 60
          command: python main.py && python weston_test.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stewartby_fixtures.xml weston_test.xml
          git commit -m "Update feeds" || exit 0
          git push
