name: Update Stewartby Feed
on:
  schedule:
    # This runs at 08:05, 10:05, 12:05, 15:05, and 17:30 UTC
    - cron: '05 08,10,12,15 * * *'
    - cron: '30 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 feedgen

      - name: Run scraper (with 3 retries)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 60
          command: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add stewartby_fixtures.xml
          git commit -m "Update fixtures" || exit 0
          git push
