name: Update Feed
on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8am
  workflow_dispatch:      # Allows you to run it manually
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 feedgen
      - name: Run Scraper
        run: python main.py
      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add stewartby_fixtures.xml
          git commit -m "Update fixtures" || exit 0
          git push
